providers = ["php"]

[variables]
NIXPACKS_PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction"
]

[start]
cmd = "php -S 0.0.0.0:$PORT index.php"